add folding apps
labdao/plex pull request #114
Opened 2023-02-28 20:53 UTC by NiklasTR

2023-03-01 18:00 UTC, thetechnocrat-dev commented
@NiklasTR can you update this branch with main and put a Loom or directions for testing?

2023-03-03 12:20 UTC, NiklasTR commented
The branch is now up to date. After making sure the IFPS configuration is correct, run

```
bacalhau docker run --selector owner=labdao --gpu 1  --network full -i QmV18Lsn5QyFuZ1z1K24rt3eC7K5o1JsijNR3LPEgV27Bm public.ecr.aws/p7l9w5o7/colabfold:latest -- /bin/bash -c 'colabfold_batch --max-msa 32:64 --templates --num-recycle 1 /inputs /outputs/'
```

You can't run: 
```
./plex -app colabfold-mini -input-dir testdata/folding -gpu=true
```
Because the networking flag is not set right now

2023-03-03 12:55 UTC, NiklasTR commented
Here are results:

```
bacalhau docker run --selector owner=labdao --gpu 1  --network full -i QmV18Lsn5QyFuZ1z1K24rt3eC7K5o1JsijNR3LPEgV27Bm public.ecr.aws/p7l9w5o7/colabfold:latest -- /bin/bash -c 'colabfold_batch --max-msa 32:64 --templates --num-recycle 1 /inputs /outputs/'
Job successfully submitted. Job ID: c85921ce-8d1f-4676-b54c-afbff085016a
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

           Communicating with the network  ................ done ✅  0.0s
              Finding node(s) for the job  ................ done ✅  0.0s
                          Running the job  ................ done ✅  10m00.2s
                          
                          
                          
bacalhau get c85921ce
```

2023-03-03 18:43 UTC, thetechnocrat-dev requested changes
It did run 🥳 . One small change requested.

<img width="612" alt="Screen Shot 2023-03-03 at 11 35 44 AM" src="https://user-images.githubusercontent.com/9427089/222801450-6ce1b0f9-27a2-47b7-a2a3-97072c5f3f3e.png">

2023-03-03 18:43 UTC, thetechnocrat-dev commented on cmd/plex/utils.go
> +	if appConfig.InputMethod == "directory" {
I'm guessing this if statement logic is a typo?

should be `appConfig.Inputmethod != "directory"` or just put it in an else block attached to the first if statement.

2023-03-03 19:52 UTC, NiklasTR commented on cmd/plex/utils.go
> +	if appConfig.InputMethod == "directory" {
thank you - yes, I was lazy when patching this late in the day

2023-03-03 20:04 UTC, NiklasTR reviewed
reviewed

2023-03-03 20:13 UTC, thetechnocrat-dev approved these changes

2023-03-03 20:15 UTC, merged