rough draft works
labdao/plex pull request #197
Opened 2023-03-22 20:24 UTC by thetechnocrat-dev

2023-03-23 09:12 UTC, NiklasTR commented
I have moved the proto-CWL configs for 0.5 to a separate PR referenced in #198

2023-03-23 12:51 UTC, NiklasTR commented on scripts/ligase/README.md
I am not sure wether ligase is the most accurate name in the mid-term, as the task for the container will be to identify outputs / their types - rather than to actually stick them together.

2023-03-23 12:57 UTC, NiklasTR requested changes
I left some reviews. The big points: 
- [ ] I suggest we move the tool definition functions and tests to a dedicated tool.go
- [ ] why not have the ligase container run all of PLEX?

2023-03-23 12:57 UTC, NiklasTR commented on scripts/ligase/ligase.go
> +import (
I propose to move this function into a dedicated file called tool.go that is focused on reading the tool definition. We will also need to read the tool definition when constructing the instructions, that's why I think moving it into a dedicated location makes sense.

2023-03-23 12:57 UTC, NiklasTR commented on scripts/ligase/dockerfile
for simplicity, could the "ligase" container not simply build all of PLEX?

2023-03-23 12:57 UTC, NiklasTR commented on scripts/ligase/ligase_test.go
I would also move the test to a dedicated tool.go file (see above)

2023-04-06 17:43 UTC, thetechnocrat-dev commented
Stale

2023-04-06 17:43 UTC, closed without merging