`plex_run` adds "python" annotation by default
labdao/plex pull request #600
Opened 2023-08-15 05:55 UTC by acashmoney

The `plex_run` command now automatically includes a "python" annotation by default. This is to distinguish between using plex in Python and Go for analytics purposes.

**To test:**
```
cd python/dev
pip install -e ../
python example.py
```

2023-08-15 05:58 UTC, acashmoney commented
@hevans66 what (if any) downstream effects does this change for our metabase queries?

2023-08-15 17:13 UTC, hevans66 commented on python/src/plex/__init__.py
> +        annotations.append("python")
Its arguable whether your intended effect is to mutate whatever list was passed in. Since I feel like this "python" is an internal annotation I would change this to `annotations = annotations + ["python"]`. That way we don't mutate the list of annotations a user gave us. This a very nitpick thing though, feel free to leave this.

2023-08-15 22:50 UTC, acashmoney commented on python/dev/example.py
> +custom_annotations = ["custom1", "custom2"]
Good call. Also replacing "custom1" with "test" so we filter all these runs out.

2023-08-15 23:54 UTC, hevans66 requested changes

2023-08-15 23:54 UTC, hevans66 commented on python/src/plex/__init__.py
> +    cmd.append(f"--annotations={','.join(annotations)}")
Staring at this more closely. I don't think it woks. Its causing one big string with commas in it, instead of a list of strings.

I believe there is nothing in the cobra go package that would separate these out into individual strings from the annotations comma separated list. Instead we need to pass the same flag multiple times to have it interpret it as an array. 

I think this needs to look something like

```python
cmd.append([f"-a={annotation}" for annotation in annotations])
```

2023-08-17 19:03 UTC, acashmoney commented on python/src/plex/__init__.py
> +    cmd.append(f"--annotations={','.join(annotations)}")
Thanks for flagging @hevans66. This change should fix it so we get a new string for each annotation. Each string makes up an individual element in the golang array.

https://github.com/labdao/plex/blob/2362adbe8b111a6dc6a30e7f561f130cd79a2db6/python/src/plex/__init__.py#L180-L184

![Screenshot_2023-08-17_at_2 31 15_PM](https://github.com/labdao/plex/assets/29086101/8a3e1d25-fcbf-482a-b572-ce9deecaae52)

2023-08-17 20:04 UTC, hevans66 approved these changes
:ship: :it:

2023-08-17 22:02 UTC, acashmoney commented
Vercel check can be ignored

2023-08-17 22:03 UTC, merged